spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: PicaPau321#
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true #para mostrar o sql que vai ser gerado no console
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
